version: "3.9"

volumes:
  postgres_data: {}

services:
  app: &app
    build:
      context: ./blog-backend
      dockerfile: Dockerfile
      args:
        DEBIAN_FRONTEND: noninteractive
        BASE_DIR: /usr/src/app/
    env_file:
      - ./blog-backend/.env
    ports:
      - "8000:8000"
    command: sh entrypoint.sh

    healthcheck:
      test: curl -s -XGET 'http://app:8000/'
      interval: 10s
      timeout: 3s
      retries: 10
    depends_on:
      - postgres



  postgres:
    build:
      context: ./blog-backend/postgres/
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - blog-backend/.env
    healthcheck:
        test:  pg_isready
        interval: 10s
        timeout: 3s
        retries: 10


